services:
  nextjs-app:
    image: node:20.11.0
    container_name: nextjs-container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:root@postgres-db:5432/project-manager
    command: "npm run dev"
    networks:
      - project-manager-network

  postgres-db:
    image: postgres:13
    container_name: postgres-container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'project-manager'
    ports:
      - "5432:5432"
    networks:
      - project-manager-network

networks:
  project-manager-network:
    driver: bridge

volumes:
  postgres-data:
